import java.sql.*;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Admin.java
 *
 * Created on 5 Nov, 2015, 7:50:37 PM
 */

/**
 *
 * @author Shreyash Haritashya
 */
public class Admin extends javax.swing.JFrame {

    /** Creates new form Admin */
    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        jD1.setLocationRelativeTo(null);
        jD2.setLocationRelativeTo(null);
        Feedback.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jD1 = new javax.swing.JDialog();
        jp4 = new javax.swing.JPanel();
        jcb37 = new javax.swing.JCheckBox();
        jcb38 = new javax.swing.JCheckBox();
        jcb39 = new javax.swing.JCheckBox();
        jcb40 = new javax.swing.JCheckBox();
        jcb41 = new javax.swing.JCheckBox();
        jcb42 = new javax.swing.JCheckBox();
        jcb43 = new javax.swing.JCheckBox();
        jcb44 = new javax.swing.JCheckBox();
        jcb45 = new javax.swing.JCheckBox();
        jcb46 = new javax.swing.JCheckBox();
        jcb47 = new javax.swing.JCheckBox();
        jcb48 = new javax.swing.JCheckBox();
        jc37 = new javax.swing.JComboBox();
        jc38 = new javax.swing.JComboBox();
        jc39 = new javax.swing.JComboBox();
        jc40 = new javax.swing.JComboBox();
        jc41 = new javax.swing.JComboBox();
        jc42 = new javax.swing.JComboBox();
        jc43 = new javax.swing.JComboBox();
        jc44 = new javax.swing.JComboBox();
        jc45 = new javax.swing.JComboBox();
        jc46 = new javax.swing.JComboBox();
        jc47 = new javax.swing.JComboBox();
        jc48 = new javax.swing.JComboBox();
        jt37 = new javax.swing.JTextField();
        jt38 = new javax.swing.JTextField();
        jt39 = new javax.swing.JTextField();
        jt40 = new javax.swing.JTextField();
        jt41 = new javax.swing.JTextField();
        jt42 = new javax.swing.JTextField();
        jt43 = new javax.swing.JTextField();
        jt44 = new javax.swing.JTextField();
        jt45 = new javax.swing.JTextField();
        jt46 = new javax.swing.JTextField();
        jt47 = new javax.swing.JTextField();
        jt48 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pb4 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jD2 = new javax.swing.JDialog();
        jButton9 = new javax.swing.JButton();
        jc1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Feedback = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        user = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jt1 = new javax.swing.JScrollPane();
        jta1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jr1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jr2 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        jD1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jD1.setTitle("Add Cure Formula");
        jD1.setMinimumSize(new java.awt.Dimension(1024, 500));
        jD1.getContentPane().setLayout(null);

        jp4.setMinimumSize(new java.awt.Dimension(900, 320));
        jp4.setPreferredSize(new java.awt.Dimension(1020, 320));
        jp4.setLayout(null);

        jcb37.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb37.setText("Calcarea Florica ");
        jcb37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb37MouseClicked(evt);
            }
        });
        jp4.add(jcb37);
        jcb37.setBounds(10, 70, 131, 27);

        jcb38.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb38.setText("Calcarea Phosphorica");
        jcb38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb38MouseClicked(evt);
            }
        });
        jp4.add(jcb38);
        jcb38.setBounds(10, 110, 163, 27);

        jcb39.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb39.setText("Calcarea Sulphurica");
        jcb39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb39MouseClicked(evt);
            }
        });
        jp4.add(jcb39);
        jcb39.setBounds(10, 150, 149, 27);

        jcb40.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb40.setText("Ferrum Phosphoricum");
        jcb40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb40jcb12MouseClicked(evt);
            }
        });
        jp4.add(jcb40);
        jcb40.setBounds(10, 190, 170, 27);

        jcb41.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb41.setText("Kalium Muriaticum");
        jcb41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb41MouseClicked(evt);
            }
        });
        jp4.add(jcb41);
        jcb41.setBounds(10, 230, 143, 27);

        jcb42.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb42.setText("Kalium Phosphoricum");
        jcb42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb42MouseClicked(evt);
            }
        });
        jp4.add(jcb42);
        jcb42.setBounds(10, 270, 170, 27);

        jcb43.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb43.setText("Kalium Sulphuricum");
        jcb43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb43MouseClicked(evt);
            }
        });
        jp4.add(jcb43);
        jcb43.setBounds(470, 60, 149, 27);

        jcb44.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb44.setText("Magnesium Phosphoricum");
        jcb44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb44MouseClicked(evt);
            }
        });
        jcb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb44ActionPerformed(evt);
            }
        });
        jp4.add(jcb44);
        jcb44.setBounds(470, 100, 200, 27);

        jcb45.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb45.setText("Natrum Muriaticum");
        jcb45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb45jcb10MouseClicked(evt);
            }
        });
        jp4.add(jcb45);
        jcb45.setBounds(470, 140, 149, 27);

        jcb46.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb46.setText("Natrum Phosphoricum");
        jcb46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb46jcb11MouseClicked(evt);
            }
        });
        jp4.add(jcb46);
        jcb46.setBounds(470, 180, 169, 27);

        jcb47.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb47.setText("Natrum Sulphuricum");
        jcb47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb47MouseClicked(evt);
            }
        });
        jp4.add(jcb47);
        jcb47.setBounds(470, 220, 157, 27);

        jcb48.setFont(new java.awt.Font("Tahoma", 0, 15));
        jcb48.setText("Silicea");
        jcb48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb48MouseClicked(evt);
            }
        });
        jp4.add(jcb48);
        jcb48.setBounds(470, 260, 63, 27);

        jc37.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc37.setEnabled(false);
        jp4.add(jc37);
        jc37.setBounds(190, 70, 90, 20);

        jc38.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc38.setEnabled(false);
        jp4.add(jc38);
        jc38.setBounds(190, 110, 90, 20);

        jc39.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc39.setEnabled(false);
        jp4.add(jc39);
        jc39.setBounds(190, 150, 90, 20);

        jc40.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc40.setEnabled(false);
        jp4.add(jc40);
        jc40.setBounds(190, 190, 90, 20);

        jc41.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc41.setEnabled(false);
        jp4.add(jc41);
        jc41.setBounds(190, 230, 90, 20);

        jc42.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc42.setEnabled(false);
        jp4.add(jc42);
        jc42.setBounds(190, 270, 90, 20);

        jc43.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc43.setEnabled(false);
        jp4.add(jc43);
        jc43.setBounds(680, 60, 90, 20);

        jc44.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc44.setEnabled(false);
        jp4.add(jc44);
        jc44.setBounds(680, 100, 90, 20);

        jc45.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc45.setEnabled(false);
        jp4.add(jc45);
        jc45.setBounds(680, 140, 90, 20);

        jc46.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc46.setEnabled(false);
        jp4.add(jc46);
        jc46.setBounds(680, 180, 90, 20);

        jc47.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc47.setEnabled(false);
        jp4.add(jc47);
        jc47.setBounds(680, 220, 90, 20);

        jc48.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x", "6x", "12x", "200x" }));
        jc48.setEnabled(false);
        jp4.add(jc48);
        jc48.setBounds(680, 260, 90, 20);

        jt37.setEnabled(false);
        jp4.add(jt37);
        jt37.setBounds(320, 70, 90, 20);

        jt38.setEnabled(false);
        jp4.add(jt38);
        jt38.setBounds(320, 110, 90, 20);

        jt39.setEnabled(false);
        jp4.add(jt39);
        jt39.setBounds(320, 150, 90, 20);

        jt40.setEnabled(false);
        jp4.add(jt40);
        jt40.setBounds(320, 190, 90, 20);

        jt41.setEnabled(false);
        jp4.add(jt41);
        jt41.setBounds(320, 230, 90, 20);

        jt42.setEnabled(false);
        jp4.add(jt42);
        jt42.setBounds(320, 270, 90, 20);

        jt43.setEnabled(false);
        jp4.add(jt43);
        jt43.setBounds(840, 60, 100, 20);

        jt44.setEnabled(false);
        jp4.add(jt44);
        jt44.setBounds(840, 100, 100, 20);

        jt45.setEnabled(false);
        jp4.add(jt45);
        jt45.setBounds(840, 140, 100, 20);

        jt46.setEnabled(false);
        jp4.add(jt46);
        jt46.setBounds(840, 180, 100, 20);

        jt47.setEnabled(false);
        jp4.add(jt47);
        jt47.setBounds(840, 220, 100, 20);

        jt48.setEnabled(false);
        jp4.add(jt48);
        jt48.setBounds(840, 260, 100, 20);

        jButton8.setBackground(new java.awt.Color(51, 255, 0));
        jButton8.setFont(new java.awt.Font("Tempus Sans ITC", 2, 20));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back(1).png"))); // NOI18N
        jButton8.setText("Go Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jp4.add(jButton8);
        jButton8.setBounds(829, 0, 150, 35);

        jButton6.setBackground(new java.awt.Color(0, 204, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        jButton6.setText("Add Formula");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6jButton2ActionPerformed(evt);
            }
        });
        jp4.add(jButton6);
        jButton6.setBounds(795, 340, 180, 33);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 15));
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Problem Name -");
        jp4.add(jLabel6);
        jLabel6.setBounds(10, 20, 119, 19);

        pb4.setFont(new java.awt.Font("Arial", 0, 14));
        jp4.add(pb4);
        pb4.setBounds(140, 10, 300, 30);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp4.add(jSeparator3);
        jSeparator3.setBounds(440, 60, 10, 270);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminBk.jpg"))); // NOI18N
        jp4.add(jLabel9);
        jLabel9.setBounds(0, 0, 1020, 380);

        jD1.getContentPane().add(jp4);
        jp4.setBounds(0, 10, 978, 380);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminBk.jpg"))); // NOI18N
        jD1.getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1040, 540);

        jD2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jD2.setTitle("Delete portal");
        jD2.setMinimumSize(new java.awt.Dimension(1024, 500));
        jD2.setResizable(false);
        jD2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jD2WindowOpened(evt);
            }
        });
        jD2.getContentPane().setLayout(null);

        jButton9.setBackground(new java.awt.Color(51, 255, 0));
        jButton9.setFont(new java.awt.Font("Tempus Sans ITC", 2, 20));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back(1).png"))); // NOI18N
        jButton9.setText("Go Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jD2.getContentPane().add(jButton9);
        jButton9.setBounds(870, 0, 150, 35);

        jc1.setFont(new java.awt.Font("Tahoma", 0, 20));
        jc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " Drop down to Select One " }));
        jD2.getContentPane().add(jc1);
        jc1.setBounds(480, 150, 460, 40);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 20));
        jButton2.setForeground(new java.awt.Color(0, 204, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jD2.getContentPane().add(jButton2);
        jButton2.setBounds(390, 310, 210, 70);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 30));
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Select problem to delete -");
        jD2.getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 150, 390, 40);

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 42));
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Delete old Cure Formula :");
        jD2.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 580, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminBk.jpg"))); // NOI18N
        jD2.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1030, 500);

        Feedback.setMinimumSize(new java.awt.Dimension(1024, 768));
        Feedback.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                FeedbackWindowOpened(evt);
            }
        });
        Feedback.getContentPane().setLayout(null);

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Feedback.getContentPane().add(jButton5);
        jButton5.setBounds(110, 490, 210, 73);

        user.setFont(new java.awt.Font("Tahoma", 2, 18));
        user.setForeground(new java.awt.Color(0, 0, 102));
        user.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userItemStateChanged(evt);
            }
        });
        Feedback.getContentPane().add(user);
        user.setBounds(40, 270, 340, 40);

        jButton7.setBackground(new java.awt.Color(0, 0, 204));
        jButton7.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back(1).png"))); // NOI18N
        jButton7.setText("Go Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Feedback.getContentPane().add(jButton7);
        jButton7.setBounds(0, 0, 140, 30);

        jta1.setColumns(20);
        jta1.setFont(new java.awt.Font("Georgia", 2, 26));
        jta1.setRows(5);
        jt1.setViewportView(jta1);

        Feedback.getContentPane().add(jt1);
        jt1.setBounds(410, 140, 570, 510);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top.jpg"))); // NOI18N
        Feedback.getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1020, 80);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminBk.jpg"))); // NOI18N
        jLabel12.setMaximumSize(new java.awt.Dimension(1024, 768));
        jLabel12.setMinimumSize(new java.awt.Dimension(1024, 768));
        jLabel12.setPreferredSize(new java.awt.Dimension(1024, 768));
        Feedback.getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 60, 1030, 690);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Screen");
        setIconImage(new ImageIcon("E:\\HomoD\\Images\\unedited\\icon\\ico.png").getImage());
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton10.setBackground(new java.awt.Color(0, 0, 102));
        jButton10.setForeground(new java.awt.Color(0, 0, 153));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(990, 0, 30, 29);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-2, 0, 1024, 90);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 26));
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Welcome Mr Shreyash Haritashya ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 100, 490, 30);

        jButton4.setBackground(new java.awt.Color(0, 204, 0));
        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feed.jpg"))); // NOI18N
        jButton4.setText("View FeedBacks");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(700, 560, 300, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(760, 100, 210, 180);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signout.jpg"))); // NOI18N
        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 290, 210, 33);

        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(740, 90, 250, 240);

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go.jpg"))); // NOI18N
        jButton3.setText("Proceed");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 570, 170, 30);

        buttonGroup1.add(jr1);
        jr1.setFont(new java.awt.Font("Georgia", 2, 20));
        jr1.setForeground(new java.awt.Color(0, 153, 153));
        jr1.setText(" Add New Cure Formula ");
        getContentPane().add(jr1);
        jr1.setBounds(160, 300, 280, 30);

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 26));
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("Select any one :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 180, 230, 40);

        buttonGroup1.add(jr2);
        jr2.setFont(new java.awt.Font("Georgia", 2, 20));
        jr2.setForeground(new java.awt.Color(0, 153, 153));
        jr2.setText(" Remove Old Cure Formula ");
        getContentPane().add(jr2);
        jr2.setBounds(160, 420, 280, 30);

        jSeparator2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(50, 160, 520, 450);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Administrator1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 90, 1020, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin.this.setVisible(false);
        new First_Frame().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(jr1.isSelected()==true)
{
    jD1.setVisible(true);
   
}
if (jr2.isSelected()==true)
{
   jD2.setVisible(true);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jcb40jcb12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb40jcb12MouseClicked
if(jcb40.isSelected()==true)
{
jt40.setEnabled(true);
jc40.setEnabled(true);
}
else if (jcb40.isSelected()==false)
{
 jt40.setEnabled(false);
jc40.setEnabled(false);
}         // TODO add your handling code here:
    }//GEN-LAST:event_jcb40jcb12MouseClicked

    private void jcb45jcb10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb45jcb10MouseClicked
if(jcb45.isSelected()==true)
{
jt45.setEnabled(true);
jc45.setEnabled(true);
}
else if (jcb45.isSelected()==false)
{
 jt45.setEnabled(false);
jc45.setEnabled(false);
}         // TODO add your handling code here:
    }//GEN-LAST:event_jcb45jcb10MouseClicked

    private void jcb46jcb11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb46jcb11MouseClicked
if(jcb46.isSelected()==true)
{
jt46.setEnabled(true);
jc46.setEnabled(true);
}
else if (jcb46.isSelected()==false)
{
 jt46.setEnabled(false);
jc46.setEnabled(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb46jcb11MouseClicked

    private void jButton6jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6jButton2ActionPerformed
   String pbname = pb4.getText();

        try{
            Class.forName("java.sql.Driver");
            Connection z = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
            Statement st= z.createStatement();
            if (jcb37.isSelected()==true)
            {
                a ="Calcarea Florica";

                a1=(String)jc37.getSelectedItem();
                A =Integer.parseInt( jt37.getText());
                String w ="insert into medi values('"+pbname+"','"+a+"','"+a1+"',"+A+");";
                st.executeUpdate(w);

            }
            if (jcb38.isSelected()==true) {
                b ="Calcarea Phosphorica";

                a2=(String)jc38.getSelectedItem();
                B=Integer.parseInt( jt38.getText());
                String w = "insert into medi values('"+pbname+"','"+b+"','"+a2+"',"+B+");";
                st.executeUpdate(w);
            }
            if (jcb39.isSelected()==true) {
                c ="Calcarea Sulphurica";

                a3=(String)jc39.getSelectedItem();
                C =Integer.parseInt( jt39.getText());
                String w = "insert into medi values('"+pbname+"','"+c+"','"+a3+"',"+C+");";
                st.executeUpdate(w);
            }
            if (jcb40.isSelected()==true) {
                d ="Ferrum Phosphoricum ";

                a4=(String)jc40.getSelectedItem();
                D =Integer.parseInt( jt40.getText());
                String w = "insert into medi values('"+pbname+"','"+d+"','"+a4+"',"+D+");";
                st.executeUpdate(w);
            }
            if (jcb41.isSelected()==true) {
                e ="Kalium  Muriaticum";

                a5=(String)jc41.getSelectedItem();
                E=Integer.parseInt( jt41.getText());
                String w = "insert into medi values('"+pbname+"','"+e+"','"+a5+"',"+E+");";
                st.executeUpdate(w);
            }
            if (jcb42.isSelected()==true) {
                f ="Kalium Phosphoricum";

                a6=(String)jc42.getSelectedItem();
                F=Integer.parseInt( jt42.getText());
                String w = "insert into medi values('"+pbname+"','"+f+"','"+a6+"',"+F+");";
                st.executeUpdate(w);
            }
            if (jcb43.isSelected()==true) {
                g ="Kalium Sulphuricum";

                a7=(String)jc43.getSelectedItem();
                G=Integer.parseInt( jt43.getText());
                String w = "insert into medi values('"+pbname+"','"+g+"','"+a7+"',"+G+");";
                st.executeUpdate(w);
            }
            if (jcb44.isSelected()==true) {
                h ="Magnesium Phosphoricum";

                a8=(String)jc44.getSelectedItem();
                H=Integer.parseInt( jt44.getText());
                String w = "insert into medi values('"+pbname+"','"+h+"','"+a8+"',"+H+");";
                st.executeUpdate(w);
            }
            if (jcb45.isSelected()==true) {
                i ="Natrum Muriaticum";

                a9=(String)jc45.getSelectedItem();
                I=Integer.parseInt( jt45.getText());
                String w = "insert into medi values('"+pbname+"','"+i+"','"+a9+"',"+I+");";
                st.executeUpdate(w);
            }
            if (jcb46.isSelected()==true) {
                j ="Natrum Phosphoricum ";

                a10=(String)jc46.getSelectedItem();
                J=Integer.parseInt( jt46.getText());
                String w = "insert into medi values('"+pbname+"','"+j+"','"+a10+"',"+J+");";
                st.executeUpdate(w);
            }
            if (jcb47.isSelected()==true) {
                k ="Natrum Sulphuricum";

                a11=(String)jc47.getSelectedItem();
                K=Integer.parseInt( jt47.getText());
                String w = "insert into medi values('"+pbname+"','"+k+"','"+a11+"',"+K+");";
                st.executeUpdate(w);
            }
            if (jcb48.isSelected()==true) {
                l ="Silicea";

                a12=(String)jc48.getSelectedItem();
                L=Integer.parseInt( jt48.getText());
                String w = "insert into medi values('"+pbname+"','"+l+"','"+a12+"',"+L+");";
                st.executeUpdate(w);
            }
            JOptionPane.showMessageDialog(null,"Your Prescription has been Updated" );
            jD1.dispose();

        } catch (Exception z) {
            System.out.println(z);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6jButton2ActionPerformed

    private void jcb37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb37MouseClicked
if(jcb37.isSelected()==true)
{
jt37.setEnabled(true);
jc37.setEnabled(true);    
}
else if (jcb37.isSelected()==false)
{
 jt37.setEnabled(false);
jc37.setEnabled(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb37MouseClicked

    private void jcb38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb38MouseClicked
if(jcb38.isSelected()==true)
{
jt38.setEnabled(true);
jc38.setEnabled(true);
}
else if (jcb38.isSelected()==false)
{
 jt38.setEnabled(false);
jc38.setEnabled(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb38MouseClicked

    private void jcb39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb39MouseClicked
if(jcb39.isSelected()==true)
{
jt39.setEnabled(true);
jc39.setEnabled(true);
}
else if (jcb39.isSelected()==false)
{
 jt39.setEnabled(false);
jc39.setEnabled(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb39MouseClicked

    private void jcb41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb41MouseClicked
if(jcb41.isSelected()==true)
{
jt41.setEnabled(true);
jc41.setEnabled(true);    
}
else if (jcb41.isSelected()==false)
{
 jt41.setEnabled(false);
jc41.setEnabled(false);   
}
    }//GEN-LAST:event_jcb41MouseClicked

    private void jcb42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb42MouseClicked
if(jcb42.isSelected()==true)
{
jt42.setEnabled(true);
jc42.setEnabled(true);
}
else if (jcb42.isSelected()==false)
{
jt42.setEnabled(false);
jc42.setEnabled(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb42MouseClicked

    private void jcb43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb43MouseClicked
if(jcb43.isSelected()==true)
{
jt43.setEnabled(true);
jc43.setEnabled(true);    
}
else if (jcb43.isSelected()==false)
{
 jt43.setEnabled(false);
jc43.setEnabled(false);   
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb43MouseClicked

    private void jcb44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb44MouseClicked
if(jcb44.isSelected()==true)
{
jt44.setEnabled(true);
jc44.setEnabled(true);
}
else if (jcb44.isSelected()==false)
{
 jt44.setEnabled(false);
jc44.setEnabled(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb44MouseClicked

    private void jcb48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb48MouseClicked
if(jcb48.isSelected()==true)
{
jt48.setEnabled(true);
jc48.setEnabled(true);
}
else if (jcb48.isSelected()==false)
{
 jt48.setEnabled(false);
jc48.setEnabled(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb48MouseClicked

    private void jcb47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb47MouseClicked
if(jcb47.isSelected()==true)
{
jt47.setEnabled(true);
jc47.setEnabled(true);
}
else if (jcb47.isSelected()==false)
{
 jt47.setEnabled(false);
jc47.setEnabled(false);
}         // TODO add your handling code here:
    }//GEN-LAST:event_jcb47MouseClicked

    private void jD2WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jD2WindowOpened
String t,r=null ;

        try{
        Class.forName("java.sql.Driver");
        Connection w = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= w.createStatement();
         String q = "Select prob_name from medi;";
        ResultSet rs = st.executeQuery(q);
        while(rs.next())
        {
           t = rs.getString(1);
           System.out.println(t);
          if(t.equals(r))
          {
            t = null;
          }
           else { jc1.addItem(t);  r = t ;}
        }
}
catch(Exception z)
{

}
        // TODO add your handling code here:
    }//GEN-LAST:event_jD2WindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String prob,at;
prob = (String)jc1.getSelectedItem();
at = " Drop down to Select One ";
if (prob.equals(at))
{
    JOptionPane.showMessageDialog(null,"Please select one Problem to delete It");
}
else if(prob!=null)
{
try{
        Class.forName("java.sql.Driver");
        Connection p = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= p.createStatement();
         String q = "delete from medi where prob_name = '"+prob+"' ;";
         st.executeUpdate(q);
         JOptionPane.showMessageDialog(null,"Your Data has been Deleted !!");
         jD2.dispose();

}
catch(Exception n)
{
System.out.println(n);
}
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcb44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb44ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Feedback.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Feedback.dispose();
        // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    private void FeedbackWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FeedbackWindowOpened
 try{
        Class.forName("java.sql.Driver");
        Connection p = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= p.createStatement();
        String q = "Select user_name from feedback;";
        ResultSet rs = st.executeQuery(q);
        while(rs.next())
        {

            user.addItem(rs.getString(1));
        }
}
catch (Exception w)
{
System.out.print(w);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_FeedbackWindowOpened

    private void userItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userItemStateChanged
String usn;
usn=(String) user.getSelectedItem();
try{
        Class.forName("java.sql.Driver");
        Connection p = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= p.createStatement();
        String kk="select review from feedback where user_name = '"+usn+"';";
        ResultSet rs = st.executeQuery(kk);

            while(rs.next())
            {
                jta1.append((String)rs.getString("review"));
            }


        }
catch (Exception z)
{
System.out.println(z);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_userItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    jta1.setText(" ");
        String usn1;
usn1=(String) user.getSelectedItem();
try{
        Class.forName("java.sql.Driver");
        Connection p = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= p.createStatement();
        String kk="delete from feedback where user_name = '"+usn1+"';";
        st.executeUpdate(kk);
        JOptionPane.showMessageDialog(null,usn1+"'s feedback has been deleted");

        Feedback.dispose();

        }
catch (Exception z)
{
System.out.println(z);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
jD2.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
jD1.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        

        System.exit(0);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton10ActionPerformed
Integer A,B,C,D,E,F,G,H,I,J,K,L;
    String a,b,c,d,e,f,g,h,i,j,k,l,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12;
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Feedback;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jD1;
    private javax.swing.JDialog jD2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox jc1;
    private javax.swing.JComboBox jc37;
    private javax.swing.JComboBox jc38;
    private javax.swing.JComboBox jc39;
    private javax.swing.JComboBox jc40;
    private javax.swing.JComboBox jc41;
    private javax.swing.JComboBox jc42;
    private javax.swing.JComboBox jc43;
    private javax.swing.JComboBox jc44;
    private javax.swing.JComboBox jc45;
    private javax.swing.JComboBox jc46;
    private javax.swing.JComboBox jc47;
    private javax.swing.JComboBox jc48;
    private javax.swing.JCheckBox jcb37;
    private javax.swing.JCheckBox jcb38;
    private javax.swing.JCheckBox jcb39;
    private javax.swing.JCheckBox jcb40;
    private javax.swing.JCheckBox jcb41;
    private javax.swing.JCheckBox jcb42;
    private javax.swing.JCheckBox jcb43;
    private javax.swing.JCheckBox jcb44;
    private javax.swing.JCheckBox jcb45;
    private javax.swing.JCheckBox jcb46;
    private javax.swing.JCheckBox jcb47;
    private javax.swing.JCheckBox jcb48;
    private javax.swing.JPanel jp4;
    private javax.swing.JRadioButton jr1;
    private javax.swing.JRadioButton jr2;
    private javax.swing.JScrollPane jt1;
    private javax.swing.JTextField jt37;
    private javax.swing.JTextField jt38;
    private javax.swing.JTextField jt39;
    private javax.swing.JTextField jt40;
    private javax.swing.JTextField jt41;
    private javax.swing.JTextField jt42;
    private javax.swing.JTextField jt43;
    private javax.swing.JTextField jt44;
    private javax.swing.JTextField jt45;
    private javax.swing.JTextField jt46;
    private javax.swing.JTextField jt47;
    private javax.swing.JTextField jt48;
    private javax.swing.JTextArea jta1;
    private javax.swing.JTextField pb4;
    private javax.swing.JComboBox user;
    // End of variables declaration//GEN-END:variables

}
