

import java.awt.Image;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Feedback.java
 *
 * Created on 11 Nov, 2015, 8:41:02 PM
 */

/**
 *
 * @author Shreyash Haritashya
 */
public class Feedback extends javax.swing.JFrame {

    /** Creates new form Feedback */
    public Feedback() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jt1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jr1 = new javax.swing.JRadioButton();
        jl1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jl2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("E:\\HomoD\\Images\\unedited\\icon\\ico.png").getImage());
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton7.setBackground(new java.awt.Color(0, 0, 102));
        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(990, 0, 30, 29);

        jb2.setBackground(new java.awt.Color(0, 204, 0));
        jb2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jb2.setForeground(new java.awt.Color(255, 255, 255));
        jb2.setText("Submit");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        getContentPane().add(jb2);
        jb2.setBounds(700, 660, 220, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 130, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Georgia", 2, 26));
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jt1.setViewportView(jTextArea1);

        getContentPane().add(jt1);
        jt1.setBounds(350, 130, 570, 520);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1020, 80);

        jr1.setBackground(new java.awt.Color(255, 255, 255));
        jr1.setFont(new java.awt.Font("Georgia", 3, 24));
        jr1.setForeground(new java.awt.Color(0, 0, 102));
        jr1.setText("Click here to Open ");
        jr1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jr1ItemStateChanged(evt);
            }
        });
        jr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr1ActionPerformed(evt);
            }
        });
        getContentPane().add(jr1);
        jr1.setBounds(220, 90, 280, 30);
        getContentPane().add(jl1);
        jl1.setBounds(20, 100, 180, 170);

        jSeparator3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(10, 90, 200, 190);

        jl2.setFont(new java.awt.Font("Georgia", 2, 18));
        jl2.setForeground(new java.awt.Color(0, 0, 204));
        jl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jl2);
        jl2.setBounds(10, 280, 230, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 80, 0, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jt1.setVisible(false);
jb2.setVisible(false);
jb2.setEnabled(false);

        String usname = null,Fname = null,Lname = null,img = null,gen=null,gen1,M,prob = null;
        try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= c.createStatement();
        String q = "Select First_Name,Last_Name,image from signup_forms where val =1;";
        ResultSet rs = st.executeQuery(q);
        while(rs.next())
        {
            Fname=rs.getString("First_Name");
            Lname=rs.getString("Last_Name");
            img=rs.getString("image");

        }

        ImageIcon icon= new ImageIcon(img);
        Image im = icon.getImage();
        Image myImg = im.getScaledInstance(jl1.getWidth(), jl1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(myImg);
        jl1.setIcon(newImage);
        jl2.setText(" "+Fname+" "+Lname);
        }
        catch (Exception e)
        {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jr1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Feedback.this.setVisible(false);
        new StartUp().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
 String fd,us = null;
 fd = jTextArea1.getText();
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
            Statement st= c.createStatement();
            String usn = "select User_Name from signup_forms where val = 1; ";
            ResultSet rs = st.executeQuery(usn);
            while(rs.next())
            {
                us = (String)rs.getString("User_Name");
            }
            String op = "insert into Feedback values('"+us+"','"+fd+"');";
            st.executeUpdate(op);
            JOptionPane.showMessageDialog(null,"We apreciate your views,THANK YOU");
            Feedback.this.setVisible(false);
           new StartUp().setVisible(true);
 }
 catch (Exception e)
 {
   System.out.println(e);  
 }
        // TODO add your handling code here:
}//GEN-LAST:event_jb2ActionPerformed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
jb2.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jr1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jr1ItemStateChanged
if(jr1.isSelected()==true)
{
jt1.setVisible(true);
jb2.setVisible(true);
}
else
{
jt1.setVisible(false);
jb2.setVisible(false);
}

        // TODO add your handling code here:
}//GEN-LAST:event_jr1ItemStateChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
            Statement st= c.createStatement();
            String u="update SignUp_forms set val = 0 where val =1;";
            st.executeUpdate(u);
        } catch(Exception e) {

        }

        System.exit(0);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jb2;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JRadioButton jr1;
    private javax.swing.JScrollPane jt1;
    // End of variables declaration//GEN-END:variables

}
