import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * First_Frame.java
 *
 * Created on 5 Nov, 2015, 1:41:51 PM
 */

/**
 *
 * @author Shreyash Haritashya
 */
public class First_Frame extends javax.swing.JFrame {

    /** Creates new form First_Frame */
    public First_Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
        //new ImageIcon(getClass().getResource("I:/HomoD/Images" + "/back(1).png")).getImage()
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Emergency = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Emergency.setTitle("Emergency");
        Emergency.setMinimumSize(new java.awt.Dimension(1024, 768));
        Emergency.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                EmergencyWindowOpened(evt);
            }
        });
        Emergency.getContentPane().setLayout(null);

        jButton4.setBackground(new java.awt.Color(0, 0, 204));
        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back(1).png"))); // NOI18N
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Emergency.getContentPane().add(jButton4);
        jButton4.setBounds(0, 0, 150, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top.jpg"))); // NOI18N
        Emergency.getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1024, 90);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 24));
        jLabel2.setText("Please Select Your Problem -");
        Emergency.getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 370, 40);

        jc1.setFont(new java.awt.Font("Georgia", 0, 18));
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        Emergency.getContentPane().add(jc1);
        jc1.setBounds(20, 130, 420, 30);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 24));
        jLabel3.setText("Your Presciption -");
        Emergency.getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 200, 240, 30);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Power", "Tablets Quantity"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        Emergency.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 640, 490);

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear-icon.png"))); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Emergency.getContentPane().add(jButton5);
        jButton5.setBounds(700, 680, 270, 30);

        jButton6.setBackground(new java.awt.Color(0, 153, 0));
        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go.jpg"))); // NOI18N
        jButton6.setText("Go");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Emergency.getContentPane().add(jButton6);
        jButton6.setBounds(460, 130, 110, 30);

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 20));
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Happy to Help You !!");
        Emergency.getContentPane().add(jLabel4);
        jLabel4.setBounds(720, 410, 250, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doct.jpg"))); // NOI18N
        Emergency.getContentPane().add(jLabel5);
        jLabel5.setBounds(720, 120, 260, 270);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminBk.jpg"))); // NOI18N
        Emergency.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 90, 1020, 680);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Homeopathy ");
        setIconImage(new ImageIcon("E:\\HomoD\\Images\\unedited\\icon\\ico.png").getImage());
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName(""); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton7.setBackground(new java.awt.Color(0, 0, 102));
        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(490, 320, 30, 29);

        jButton2.setFont(new java.awt.Font("Georgia", 3, 20));
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmergencyButton-300x300.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 90, 110, 100);

        jButton1.setFont(new java.awt.Font("Georgia", 3, 48));
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 510, 50);

        jButton3.setFont(new java.awt.Font("Georgia", 3, 48));
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/join.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(510, 0, 510, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_0852.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 1024, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
First_Frame.this.setVisible(false);
LogIn fr1 = new LogIn();
fr1.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
First_Frame.this.setVisible(false);
Emergency.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
 JFrame fm = new JFrame("First_Frame");
               String img ="C:/Users/Shreyash Haritashya/Desktop/HomoD/Images/unedited/a.png";
              ImageIcon icon= new ImageIcon(img);
              Image im = icon.getImage();
              fm.setIconImage(im);

        try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= c.createStatement();

        String q = "create table if not exists SignUp_Forms(First_Name varchar(20) not null ,Last_Name varchar(20) not null ,Age int(4) not null, Phone_No varchar(100) not null ,Address varchar(100) not null,Gender varchar(1) not null,User_Name varchar(30) not null,Password varchar(30) not null ,Security_question varchar(50) not null,Security_Answer varchar(50) not null,val int(4),image varchar(500), primary key (User_Name))engine = innodb; ";
        st.executeUpdate(q);
        //System.out.println("signup_forms table has been created");

        String a = "create table if not exists Feedback(user_name varchar(30), review varchar(1000));";
        st.executeUpdate(a);
        //System.out.println("Feedback table has been created");

        String b = "create table if not exists medi(prob_name varchar(30),medicine varchar(1000),power varchar(5),quantity int(5));";
        st.executeUpdate(b);
        //System.out.println("Medi table has been created");

        String l = "create table if not exists prescription(user_name varchar(30),prob_name varchar(30),medicine varchar(1000),power varchar(5),quantity int(5),date_time varchar(50));";
        st.executeUpdate(l);
        //System.out.println("Prescription table has been created");

         }
        catch(Exception e)
        {
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
First_Frame.this.setVisible(false);
new SignUp().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Emergency.dispose();
        new First_Frame().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel m = (DefaultTableModel)tb1.getModel();
        int n = m.getRowCount();
        for(int i=0;i<n;i++) {
            m.removeRow(0);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed
int j;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed


        String prob;
        DefaultTableModel m = (DefaultTableModel)tb1.getModel();
        prob = (String)jc1.getSelectedItem();

       int n = m.getRowCount();

        
           if(n>0)
           {
               
                 
                 for(int k=0;k<n;k++)
                 {
                 m.removeRow(0);
                 }
              n=0;
               try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
            Statement st= c.createStatement();
            String q = "Select medicine,power,quantity from medi where prob_name = '"+prob+"' ;";
            ResultSet rs = st.executeQuery(q);
            while(rs.next()) {

                String Mname = rs.getString("medicine");
                String Pw = rs.getString("power");
                String Qu = rs.getString("quantity");
                m.addRow(new Object[]
                {
                    Mname,Pw,Qu
                });
                j=1;
            }
        } catch (Exception e) {

        }
              
           }
           else if(n==0)
           {
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
            Statement st= c.createStatement();
            String q = "Select medicine,power,quantity from medi where prob_name = '"+prob+"' ;";
            ResultSet rs = st.executeQuery(q);
            while(rs.next()) {

                String Mname = rs.getString("medicine");
                String Pw = rs.getString("power");
                String Qu = rs.getString("quantity");
                m.addRow(new Object[]
                {
                    Mname,Pw,Qu
                });
                j=1;
            }
        } catch (Exception e) {

        }
           }
       
        // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc1ActionPerformed

    private void EmergencyWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_EmergencyWindowOpened
String t,r=null ;

        try{
        Class.forName("java.sql.Driver");
        Connection w = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= w.createStatement();
         String q = "Select prob_name from medi;";
        ResultSet rs = st.executeQuery(q);
        while(rs.next())
        {
           t = rs.getString(1);
          if(t.equals(r))
          {
            t = null;
          }
           else { jc1.addItem(t);  r = t ;}
        }
}
catch(Exception z)
{

}
        // TODO add your handling code here:
    }//GEN-LAST:event_EmergencyWindowOpened

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_Frame().setVisible(true);

              
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Emergency;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jc1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

}
