import java.sql.*;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Medicines.java
 *
 * Created on 5 Nov, 2015, 7:26:02 PM
 */

/**
 *
 * @author Shreyash Haritashya
 */
public class Medicines extends javax.swing.JFrame {

    /** Creates new form Medicines */
    public Medicines() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jd2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jd1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Medicines Information");
        setIconImage(new ImageIcon("E:\\HomoD\\Images\\unedited\\icon\\ico.png").getImage());
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jButton7.setBackground(new java.awt.Color(0, 0, 102));
        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(980, 0, 30, 29);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 130, 30);
        getContentPane().add(jd2);
        jd2.setBounds(350, 480, 160, 190);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1024, 90);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 30));
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Details will be shown here \\/ ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 130, 440, 30);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 20));
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Click on Medicines to know about It !.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 380, 400, 28);

        jd1.setColumns(20);
        jd1.setFont(new java.awt.Font("Monospaced", 0, 24));
        jd1.setForeground(new java.awt.Color(51, 0, 51));
        jd1.setRows(5);
        jScrollPane4.setViewportView(jd1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(40, 170, 480, 300);

        jl1.setFont(new java.awt.Font("Comic Sans MS", 2, 24));
        jl1.setForeground(new java.awt.Color(0, 204, 204));
        jl1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Calcarea Florica", "Calcarea Phosphorica", "Calcarea Sulphurica", "Ferrum Phosphoricum", "Kalium Muriaticum", "Kalium Phosphoricum", "Kalium Sulphuricum", "Magnesium Phosphoricum", "Natrum Muriaticum", "Natrum Phosphoricum", "Natrum Sulphuricum", "Silicea" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jl1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jl1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jl1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jl1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(590, 410, 390, 290);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 170, 480, 510);

        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 120, 540, 590);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 130, 360, 230);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(590, 120, 380, 250);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminBk.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 90, 1020, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Medicines.this.setVisible(false);
        new StartUp().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jl1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jl1ValueChanged
String img;
        int a;
a= jl1.getSelectedIndex();
        String fn1;



switch(a)
{
    case 0 : jd1.setText("Its specially good for - problems  " +
                         "\n"+"like"+
                         "\n" + "Glands Swelling"
                         +"\n" +  "Dilation of Heart" +
                         "\n" + "Adenoids" );
              img ="E:/HomoD/Images/calcarea-fluorica.jpg";
              ImageIcon icon= new ImageIcon(img);
              Image im = icon.getImage();
              ImageIcon newImage = new ImageIcon(im);
              jd2.setIcon(newImage);
              break;

    case 1 : jd1.setText("Its specially good for - problems" +
            "\n"+"like -"+
            "\n" + "Canvalescence"
                         +"\n" +  "Anaemia" +
                         "\n" + "Rickets"+
                         "\n" + "Gallstones");
              img ="E:/HomoD/Images/calcarea-phosphorica.jpg";
              ImageIcon icon1= new ImageIcon(img);
              Image im1 = icon1.getImage();
              ImageIcon newImage1 = new ImageIcon(im1);
              jd2.setIcon(newImage1);
              break;

    case 2 : jd1.setText("When formula which is given"
                          + "\n" + "is not working properly,"
                          + "\n" +"then give ,this medicine"+
                          "\n " + "folling give earlier formula again");
              img ="E:/HomoD/Images/calcarea-sulphurica.jpg";
              ImageIcon icon2= new ImageIcon(img);
              Image im2 = icon2.getImage();
              ImageIcon newImage2 = new ImageIcon(im2);
              jd2.setIcon(newImage2);
              break;
case 3 : jd1.setText("Its specially good for - problems " +
        "\n"+"like -"+
                         "\n" + "Fever"
                         +"\n" +  "Stopping blood flow" +
                         "\n" + "Cold");
              img ="E:/HomoD/Images/ferrum-phosphoricum-.jpg";
              ImageIcon icon3= new ImageIcon(img);
              Image im3 = icon3.getImage();
              ImageIcon newImage3 = new ImageIcon(im3);
              jd2.setIcon(newImage3);
              break;
case 4 : jd1.setText("Its specially good for - problems" +
        "\n"+"like -"+
                         "\n" + "Eye problems"
                         +"\n" +  "stomach Problems" );

              img ="E:/HomoD/Images/kalium-muriaticum.jpg";
              ImageIcon icon4= new ImageIcon(img);
              Image im4 = icon4.getImage();
              ImageIcon newImage4 = new ImageIcon(im4);
              jd2.setIcon(newImage4);
              break;
case 5 : jd1.setText("Its specially good for - problems" +
        "\n"+"like -"+
                         "\n" + "Spetic"
                         +"\n" +  "Mental Problems" );
              img ="E:/HomoD/Images/kalium-phosphoricum.jpg";
              ImageIcon icon5= new ImageIcon(img);
              Image im5 = icon5.getImage();
              ImageIcon newImage5 = new ImageIcon(im5);
              jd2.setIcon(newImage5);
              break;
case 6 : jd1.setText("Its specially good for - problems " +
        "\n"+"like -"+
                         "\n" + "Eruptions"
                         +"\n" +  "Suppress" );
              img ="E:/HomoD/Images/kalium-sulphuricum.jpg";
              ImageIcon icon6= new ImageIcon(img);
              Image im6 = icon6.getImage();
              ImageIcon newImage6 = new ImageIcon(im6);
              jd2.setIcon(newImage6);
              break;
case 7 : jd1.setText("Its specially good for - problems" +
        "\n"+"like -"+
                         "\n" + "Spasms"
                         +"\n" +  "T.V" );
              img ="E:/HomoD/Images/magnesium-phosphoricum.jpg";
              ImageIcon icon7= new ImageIcon(img);
              Image im7 = icon7.getImage();
              ImageIcon newImage7 = new ImageIcon(im7);
              jd2.setIcon(newImage7);
              break;
case 8 : jd1.setText("Its specially good for - problems" +
        "\n"+"like -"+
                         "\n" + "Controlling tears "
                         +"\n" +  "Loo (in summers)" );
              img ="E:/HomoD/Images/natrum-muriaticum.jpg";
              ImageIcon icon8= new ImageIcon(img);
              Image im8 = icon8.getImage();
              ImageIcon newImage8 = new ImageIcon(im8);
              jd2.setIcon(newImage8);
              break;
case 9 : jd1.setText("Its specially good for - problems" +
        "\n"+"like -"+
                         "\n" + "Jaundice"
                         +"\n" +  "Phobia" );
              img ="E:/HomoD/Images/natrum-phosphoricum.jpg";
              ImageIcon icon9= new ImageIcon(img);
              Image im9 = icon9.getImage();
              ImageIcon newImage9 = new ImageIcon(im9);
              jd2.setIcon(newImage9);
              break;
case 10 : jd1.setText("Its specially good for - problems" +
        "\n"+"like -"+
                         "\n" + "Suicide"
                         +"\n" +  "Breathing problems" );
              img ="E:/HomoD/Images/natrum-sulphuricum.jpg";
              ImageIcon icon10= new ImageIcon(img);
              Image im10 = icon10.getImage();
              ImageIcon newImage10 = new ImageIcon(im10);
              jd2.setIcon(newImage10);
              break;
case 11 : jd1.setText("Its specially good for - problems" +
        "\n"+"like -"+
                         "\n" + "Pimples"
                         +"\n" +  "Skin Problems" );
              img ="E:/HomoD/Images/silicea-homeopathic-medicine.jpg";
              ImageIcon icon11= new ImageIcon(img);
              Image im11 = icon11.getImage();
              ImageIcon newImage11 = new ImageIcon(im11);
              jd2.setIcon(newImage11);
              break;

}
 
 

        // TODO add your handling code here:
}//GEN-LAST:event_jl1ValueChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= c.createStatement();
        String u="update SignUp_forms set val = 0 where val =1;";
            st.executeUpdate(u);
}
catch(Exception e)
{

}

        System.exit(0);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jd1;
    private javax.swing.JLabel jd2;
    private javax.swing.JList jl1;
    // End of variables declaration//GEN-END:variables

}
