import java.sql.*;
import javax.swing.*;
import java.awt.Image;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;
import java.awt.print.*;
import javax.swing.JTable;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prescription.java
 *
 * Created on 6 Nov, 2015, 3:32:56 PM
 */

/**
 *
 * @author Shreyash Haritashya
 */
public class Prescription extends javax.swing.JFrame {

    /** Creates new form Prescription */
    public Prescription() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jl3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jl1 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Presciption");
        setIconImage(new ImageIcon("E:\\HomoD\\Images\\unedited\\icon\\ico.png").getImage());
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton7.setBackground(new java.awt.Color(0, 0, 102));
        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(990, 0, 30, 29);

        jl3.setFont(new java.awt.Font("Tahoma", 0, 14));
        getContentPane().add(jl3);
        jl3.setBounds(690, 200, 320, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 130, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-2, 0, 1024, 90);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24));
        jLabel1.setText("Please Select  from Your Saved Problems :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 580, 40);
        getContentPane().add(jl1);
        jl1.setBounds(720, 90, 70, 60);

        jl2.setFont(new java.awt.Font("Georgia", 2, 18));
        jl2.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(jl2);
        jl2.setBounds(790, 90, 230, 60);

        jc1.setFont(new java.awt.Font("Georgia", 0, 18));
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jc1);
        jc1.setBounds(10, 130, 560, 30);

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go.jpg"))); // NOI18N
        jButton3.setText("Go");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 130, 110, 30);

        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(720, 90, 300, 60);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time/Date", "Medicine Name", "Power", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 670, 560);

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.jpg"))); // NOI18N
        jButton2.setText("Print Presciption");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(700, 550, 270, 40);

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear-icon.png"))); // NOI18N
        jButton4.setText("Clear Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(700, 470, 220, 40);

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dele1.jpg"))); // NOI18N
        jButton5.setText("Remove Presciption");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(700, 630, 280, 41);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminBk.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 90, 1020, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Prescription.this.setVisible(false);
        new StartUp().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc1ActionPerformed
String j;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String prob,dt = null;
        DefaultTableModel m = (DefaultTableModel)tb1.getModel();
        prob = (String)jc1.getSelectedItem();
        String usname = null;

        int n = m.getRowCount();

        if(n>0)
        {

            jl3.setText("");


        for(int i=0;i<n;i++) {
            m.removeRow(0);
        }

        try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= c.createStatement();

         String h = "Select User_Name from signup_forms where val = 1; ";
        ResultSet zx = st.executeQuery(h);
        while(zx.next())
        {
            usname=zx.getString("User_Name");
        }



        String q = "Select medicine,power,quantity,date_time from prescription where prob_name = '"+prob+"' and user_name = '"+usname+"';";
        ResultSet rs = st.executeQuery(q);
        while(rs.next())
        {
           dt = rs.getString("date_time");
           String Mname = rs.getString("medicine");
           String Pw = rs.getString("power");
           String Qu = rs.getString("quantity");
        m.addRow(new Object[]
            {
                Mname,Pw,Qu
            });
        }
        jl3.setText("Saved Date & Time - "+dt);

}
catch (Exception e)
{

}
        }
            else if (n==0)
            {
                 jl3.setText("");


        for(int i=0;i<n;i++) {
            m.removeRow(0);
        }

        try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= c.createStatement();

         String h = "Select User_Name from signup_forms where val = 1; ";
        ResultSet zx = st.executeQuery(h);
        while(zx.next())
        {
            usname=zx.getString("User_Name");
        }



        String q = "Select medicine,power,quantity,date_time from prescription where prob_name = '"+prob+"' and user_name = '"+usname+"';";
        ResultSet rs = st.executeQuery(q);
        while(rs.next())
        {
           dt = rs.getString("date_time");
           String Mname = rs.getString("medicine");
           String Pw = rs.getString("power");
           String Qu = rs.getString("quantity");
        m.addRow(new Object[]
            {
                Mname,Pw,Qu
            });
        }
        jl3.setText("Saved Date & Time - "+dt);

}
catch (Exception e)
{

}
            }
        
        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
String usname = null,Fname = null,Lname = null,img = null,gen=null,gen1,M,prob = null;
        try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= c.createStatement();
        String q = "Select User_Name,First_Name,Last_Name,image from signup_forms where val =1;";
        ResultSet rs = st.executeQuery(q);
        while(rs.next())
        {
            usname = rs.getString("User_Name");
            Fname=rs.getString("First_Name");
            Lname=rs.getString("Last_Name");
            img=rs.getString("image");

        }

        ImageIcon icon= new ImageIcon(img);
        Image im = icon.getImage();
        Image myImg = im.getScaledInstance(jl1.getWidth(), jl1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(myImg);
        jl1.setIcon(newImage);
        jl2.setText(" "+Fname+" "+Lname);
        }
        catch (Exception e)
        {

        }
        String tkid;
        Object t;
        Object r = null;

         try{
        Class.forName("java.sql.Driver");
        Connection w = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= w.createStatement();
         String q = "Select prob_name from prescription where user_name = '"+usname+"';";
        ResultSet rs = st.executeQuery(q);
        while(rs.next())
        {
           t = rs.getString(1);
             if(t.equals(r))
          {
            t = null;
          }
           else { jc1.addItem(t);  r = t ;}
        }
}
catch(Exception z)
{

}




        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MessageFormat header = new MessageFormat("Page {0,number,integer}");
        MessageFormat footer = new MessageFormat("TID 5013 Assignment #1");
        try {
            //table.print(JTable.PrintMode.FIT_WIDTH, header, null);
            tb1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }
        catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jl3.setText("");
        DefaultTableModel m = (DefaultTableModel)tb1.getModel();
        int n = m.getRowCount();
        for(int i=0;i<n;i++) {
            m.removeRow(0);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String usname = null;
        String prob = (String) jc1.getSelectedItem();
        
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
            Statement st= c.createStatement();
              
              String k = "Select User_Name from signup_forms where val = 1; ";

        ResultSet zx = st.executeQuery(k);
        while(zx.next())
        {
            usname=zx.getString("User_Name");
        }
              String z ="delete from prescription where prob_name = '"+prob+"' and user_name = '"+usname+"';";
              st.executeUpdate(z);
               
       
              JOptionPane.showMessageDialog(null, "Your Presciption has been Deleted");
              Prescription.this.setVisible(false);
        new StartUp().setVisible(true);
              
        }
        catch(Exception e)
        {
System.out.println(e);
        }

        // TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
            Statement st= c.createStatement();
            String u="update SignUp_forms set val = 0 where val =1;";
            st.executeUpdate(u);
        } catch(Exception e) {

        }

        System.exit(0);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox jc1;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl3;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

}
