import java.awt.Image;
import java.io.File;
import java.sql.*;
import javax.swing.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SignUp.java
 *
 * Created on 5 Nov, 2015, 2:09:15 PM
 */

/**
 *
 * @author Shreyash Haritashya
 */
public class SignUp extends javax.swing.JFrame {

    /** Creates new form SignUp */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fname = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        usname = new javax.swing.JTextField();
        sans = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        p2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        questions = new javax.swing.JComboBox();
        jb1 = new javax.swing.JButton();
        jmale = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jfemale = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sign Up");
        setIconImage(new ImageIcon("E:\\HomoD\\Images\\unedited\\icon\\ico.png").getImage());
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton7.setBackground(new java.awt.Color(0, 0, 102));
        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(990, 0, 30, 29);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back(1).png"))); // NOI18N
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 140, 30);

        fname.setFont(new java.awt.Font("Tahoma", 0, 18));
        getContentPane().add(fname);
        fname.setBounds(150, 110, 290, 28);

        add.setFont(new java.awt.Font("Tahoma", 0, 18));
        getContentPane().add(add);
        add.setBounds(230, 320, 740, 30);

        age.setFont(new java.awt.Font("Tahoma", 0, 18));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age);
        age.setBounds(150, 190, 290, 28);

        lname.setFont(new java.awt.Font("Tahoma", 0, 18));
        getContentPane().add(lname);
        lname.setBounds(150, 150, 290, 28);

        usname.setFont(new java.awt.Font("Tahoma", 0, 18));
        getContentPane().add(usname);
        usname.setBounds(260, 470, 310, 28);

        sans.setFont(new java.awt.Font("Tahoma", 0, 18));
        getContentPane().add(sans);
        sans.setBounds(270, 670, 310, 28);

        phno.setFont(new java.awt.Font("Tahoma", 0, 18));
        getContentPane().add(phno);
        phno.setBounds(210, 260, 300, 28);

        p1.setFont(new java.awt.Font("Tahoma", 0, 18));
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1);
        p1.setBounds(260, 520, 310, 28);

        p2.setFont(new java.awt.Font("Tahoma", 0, 18));
        getContentPane().add(p2);
        p2.setBounds(260, 570, 310, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("First Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 110, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setText("Address :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 320, 100, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel3.setText("Age :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 190, 56, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel4.setText("Last Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 150, 130, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel5.setText("Answer :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 670, 94, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel6.setText("Security Question :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 610, 201, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel7.setText("Password :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 520, 117, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel8.setText("Re-Type Password :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 560, 214, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel9.setText("User Name :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 470, 135, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel10.setText("Phone Number :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 260, 173, 29);

        questions.setFont(new java.awt.Font("Tahoma", 0, 18));
        questions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select a Question ...", "My first pet name ?", "My Birthplace ?", "Bestfriend's name ?", "What I like most ?", "Place I wanna go ? " }));
        getContentPane().add(questions);
        questions.setBounds(270, 620, 310, 30);

        jb1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36));
        jb1.setForeground(new java.awt.Color(0, 0, 51));
        jb1.setText("Lets Proceed.....");
        jb1.setEnabled(false);
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        getContentPane().add(jb1);
        jb1.setBounds(650, 680, 350, 40);

        buttonGroup1.add(jmale);
        jmale.setFont(new java.awt.Font("Tahoma", 0, 18));
        jmale.setText("Male");
        getContentPane().add(jmale);
        jmale.setBounds(220, 400, 61, 31);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel11.setText("Gender -");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 360, 110, 29);

        buttonGroup1.add(jfemale);
        jfemale.setFont(new java.awt.Font("Tahoma", 0, 18));
        jfemale.setText("Female");
        getContentPane().add(jfemale);
        jfemale.setBounds(340, 400, 81, 31);

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14));
        jButton3.setText("Add Profile Picture ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(780, 280, 190, 27);

        image1.setBounds(0, 0, 270, 160);
        jDesktopPane1.add(image1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(730, 110, 270, 160);

        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 100, 1010, 630);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminBk.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 100, 1010, 630);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/top.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1020, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
SignUp.this.setVisible(false);
new First_Frame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed


     try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= c.createStatement();

        String gen=null,pass=null,ques=null;
        ques = (String) questions.getSelectedItem();
        String same = "Please select a Question ...";
        if(ques.equals(same))
        {
            JOptionPane.showMessageDialog(null,"Please Select your Security Question");
        }

                if(jmale.isSelected()==true)
        {
            gen = "M";
        }
        else if (jfemale.isSelected()==true)
        {
            gen = "F";
        }
        else if(jmale.isSelected()==false && jfemale.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null,"Please Select your Gender");
        }
        String ps,rps;
        ps = new String (p1.getPassword());
        rps =new String (p2.getPassword());
        if (ps==null||rps==null)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Password");
        }
        {
          if(ps.equals(rps))
            {
             pass=ps;
            }
          else JOptionPane.showMessageDialog(null,"Your password is not Matching!!!!(Default password is being set i.e 'null') You can modify it later");
        }
        int AGE=0;
        AGE = Integer.parseInt(age.getText());
         if (AGE==0)
        {
            JOptionPane.showMessageDialog(null,"Please Enter your Age");
        }

       String  Phno =(phno.getText());
         if (Phno==null)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Phone Number");
        }
         String fn=null,ln=null,ad=null,usn=null,san=null;
         fn =fname.getText();
         ln = lname.getText();
         ad=add.getText();
         usn=usname.getText();
         san=sans.getText();
         if(fn==null||ln==null||ad==null||usn==null||san==null)
         {
             JOptionPane.showMessageDialog(null,"Please Enter all the Details Correctly");
         }
        String v = "insert into SignUp_Forms values("
                + "'" + fn + "'" + ","
                + "'" + ln + "'" + ","
                + AGE + ","
                +"'"+ Phno+"'"+ ","
                + "'" + ad + "'" + ","
                + "'" + gen + "'" + ","
                + "'" + usn + "'" + ","
                + "'" + pass + "'" + ","
                + "'" + ques + "'" + ","
                + "'" + san + "',"
                + "0,'" + fn1 +"');" ;
       st.executeUpdate(v);
       fname.setText("");
       lname.setText("");
       p1.setText("");
       p2.setText("");
       sans.setText("");
       usname.setText("");
       phno.setText("");
       age.setText("");
       add.setText("");
       int an= JOptionPane.showConfirmDialog(null,"CONGRATULATIONS,Your Account has been created, Do you want to LogIn now " );
       if (an==JOptionPane.YES_OPTION)
       {
           SignUp.this.setVisible(false);
           new LogIn().setVisible(true);
       }
       if (an==JOptionPane.NO_OPTION)
       {
           SignUp.this.setVisible(false);
           new First_Frame().setVisible(true);
       }

                }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
}//GEN-LAST:event_jb1ActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed
String filename,fn1;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        //System.out.println(filename);
        fn1 = filename.replace("\\","/");
        image1.setText(fn1);
        ImageIcon icon= new ImageIcon(fn1);
        Image im = icon.getImage();
        Image myImg = im.getScaledInstance(image1.getWidth(), image1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(myImg);
        image1.setIcon(newImage);
        jb1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel image1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb1;
    private javax.swing.JRadioButton jfemale;
    private javax.swing.JRadioButton jmale;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JTextField phno;
    private javax.swing.JComboBox questions;
    private javax.swing.JTextField sans;
    private javax.swing.JTextField usname;
    // End of variables declaration//GEN-END:variables

}
