import java.sql.*;
import javax.swing.*;
import java.awt.Image;
import java.io.File;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Welcome_Screen.java
 *
 * Created on 6 Nov, 2015, 1:52:28 PM
 */

/**
 *
 * @author Shreyash Haritashya
 */
public class Welcome_Screen extends javax.swing.JFrame {

    /** Creates new form Welcome_Screen */
    public Welcome_Screen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jl3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Welcome Screen");
        setIconImage(new ImageIcon("E:\\HomoD\\Images\\unedited\\icon\\ico.png").getImage());
        setMinimumSize(new java.awt.Dimension(720, 700));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jl1);
        jl1.setBounds(130, 140, 460, 310);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 20));
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("\"Now every One can Cure  Themselves \"");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 110, 390, 27);

        jl2.setFont(new java.awt.Font("Arial", 3, 30));
        jl2.setForeground(new java.awt.Color(204, 0, 102));
        jl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jl2);
        jl2.setBounds(130, 440, 470, 50);

        jl3.setFont(new java.awt.Font("Tahoma", 2, 18));
        jl3.setForeground(new java.awt.Color(153, 0, 0));
        jl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jl3);
        jl3.setBounds(180, 480, 360, 40);

        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jScrollPane1.setViewportView(jSeparator1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 110, 480, 410);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("' Please wait it will just take few Seconds to Log In. '");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 640, 370, 20);

        jLabel1.setFont(new java.awt.Font("Ravie", 3, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Personal Homeopathy Doctor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 700, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sett.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 720, 680);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminBk.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        String Fname = null,Lname = null,img = null,gen=null,gen1,M;
        try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= c.createStatement();
        String q = "Select First_Name,Last_Name,image,Gender from signup_forms where val =1;";
        ResultSet rs = st.executeQuery(q);
        while(rs.next())
        {
            Fname=rs.getString("First_Name");
            Lname=rs.getString("Last_Name");
            img=rs.getString("image");
            gen = rs.getString("Gender");
        }
        M="M";
            if(gen.equals(M))
            {
              gen ="Mr";
            }
            else gen="Miss";
        
        ImageIcon icon= new ImageIcon(img);
        Image im = icon.getImage();
        Image myImg = im.getScaledInstance(jl1.getWidth(), jl1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(myImg);
        jl1.setIcon(newImage);
        jl2.setText(gen+" "+Fname+" "+Lname);
        jl3.setText("'Press Any Key to Continue'");

        
}
catch (Exception e)
{
    //System.out.println(e);

}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
try{
        Class.forName("java.sql.Driver");
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/homodoct","root","123");
        Statement st= c.createStatement();
        {
        String z = "select sleep(1);";
        st.executeQuery(z);
        }
        Welcome_Screen.this.setVisible(false);
        new StartUp().setVisible(true);
}
catch(Exception e)
{

}

        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl3;
    // End of variables declaration//GEN-END:variables

}
